const segment = {
    basic: 'سهل',
    medium: 'متوسط',
    advanced: 'صعب',
  };
  
  const quiz = {
    quizTitle: 'الاخنبار الاول',
    quizSynopsis: '',
    "questions": [
      {
        question: 'ما هو اسم المنفذ التالي؟',
        questionPic: './images/usb.png',
        questionType: 'text',
        answerSelectionType: 'single',
        answers: [
          'usb port',
          'PS/2 port',
          'display port',
          'HDMI port',
        ],
        correctAnswer: '1',
        messageForCorrectAnswer: 'اجابة صحيحة',
        messageForIncorrectAnswer: 'اجابة خاطئة',
        explanation: 'الاجابة الصحيحة هي usb port',
        point: '20',
        segment: "nice",
      },
      {
        question: 'قاعدة توصيل المعالج التكون موصلاتها على هيئة سنون تسمى؟',
        questionType: 'text',
        answerSelectionType: 'single',
        answers: [
          'BGA Socket',
          'LGA Socket',
          'PGA Socket',
        ],
        correctAnswer: '3',
        messageForCorrectAnswer: 'إجابة صحيحة برافو',
        messageForIncorrectAnswer: 'إجابة خاطئة.. حاول مرة أخرى',
        explanation: 'الإجابة الصحيحة هي PGA Socket',
        point: '25',
        segment: segment.basic,
      },
      {
        question: 'ماذا يعني ان تردد اللوحة الأم 1000 ميجاهرتز؟',
        questionType: 'text',
        answerSelectionType: 'single',
        answers: [
          'تردد الناقل الامامي يساوي 1000 ميجاهرتز',
          'تردد الناقل التسلسلي يساوي 1000 ميجاهرتز',
          'تردد الناقل الخلفي يساوي 1000 ميجاهرتز',
        ],
        correctAnswer: '1',
        messageForCorrectAnswer: 'إجابة صحيحة برافو',
        messageForIncorrectAnswer:  'إجابة خاطئة.. حاول مرة أخرى',
        explanation: 'الإجابة الصحيحة هي تردد الناقل الامامي يساوي 1000 ميجاهرتز',
        point: '30',
        segment: segment.advanced,
      },
      {
        question: 'ما هو اسم القطعة التالية؟',
        questionPic: './images/bios.jpg',
        questionType: 'text',
        answerSelectionType: 'single',
        answers: [
          'ذاكرة  CMOS',
          'شريحة الجسر الشمالي',
          'BIOS',
        ],
        correctAnswer: '3',
        messageForCorrectAnswer: 'إجابة صحيحة برافو',
        messageForIncorrectAnswer: 'إجابة خاطئة.. حاول مرة أخرى',
        explanation: 'الإجابة الصحيحة هي BIOS',
        point: '25',
        segment: segment.medium,
      },
      // {
      //   question: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
      //   questionType: 'photo',
      //   answerSelectionType: 'single',
      //   answers: [
      //     'https://dummyimage.com/600x400/000/fff&text=A',
      //     'https://dummyimage.com/600x400/000/fff&text=B',
      //     'https://dummyimage.com/600x400/000/fff&text=C',
      //     'https://dummyimage.com/600x400/000/fff&text=D',
      //   ],
      //   correctAnswer: '1',
      //   messageForCorrectAnswer: 'Correct answer. Good job.',
      //   messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      //   explanation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      //   point: '20',
      // },
      // {
      //   question: 'What are the advantages of React JS?',
      //   questionType: 'text',
      //   answerSelectionType: 'multiple',
      //   answers: [
      //     'React can be used on client and as well as server side too',
      //     'Using React increases readability and makes maintainability easier. Component, Data patterns improves readability and thus makes it easier for manitaining larger apps',
      //     'React components have lifecycle events that fall into State/Property Updates',
      //     'React can be used with any other framework (Backbone.js, Angular.js) as it is only a view layer',
      //   ],
      //   correctAnswer: [1, 2, 4],
      //   messageForCorrectAnswer: 'Correct answer. Good job.',
      //   messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
      //   explanation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      //   point: '20',
      // },
    ],
  };
  
  export default quiz;
  