const themeConfig = {
  templateName: 'Materio',
  layout: 'horizontal',
  mode: 'dark',
  direction: 'rtl',
  skin: 'default',
  contentWidth: 'boxed',
  footer: 'static',
  routingLoader: true,
  navHidden: true,
  menuTextTruncate: true,
  navSubItemIcon: 'mdi:circle-outline',
  verticalNavToggleType: 'accordion',
  navCollapsed: true,
  navigationSize: 260,
  collapsedNavigationSize: 68,
  afterVerticalNavMenuContentPosition: 'fixed',
  beforeVerticalNavMenuContentPosition: 'fixed',
  horizontalMenuToggle: 'hover',
  horizontalMenuAnimation: true,
  appBar: 'fixed',
  appBarBlur: true,
  responsiveFontSizes: true,
  disableRipple: false,
  disableCustomizer: false,
  toastPosition: 'top-right'
}
export default themeConfig
